In [16]:
import cv2
from scipy.spatial.transform import Rotation as R
import numpy as np
from numpy.linalg import  *
import math

euler = [90, 0, 0]
r = R.from_euler('XYZ', euler, degrees=True)
mat = r.as_matrix()

print(mat)
print(det(mat))
print(math.degrees(norm(cv2.Rodrigues(mat)[0])))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  2.22044605e-16]]
1.0
89.99999999999999


In [17]:
mat2 = np.array([[ 1.00000000e+00,  0.00000000e+00, 0.00000000e+00],
 [ 0.00000000e+00, 2.22044605e-2, -1.00000000e+00],
 [ 0.00000000e+00, 1.00000000e+00, 2.22044605e-2]])
print(det(mat2))
print(math.degrees(norm(cv2.Rodrigues(mat2)[0])))

1.0004930380660961
88.7279871497588
